fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

AmUserBundle:
    resource: "@AmUserBundle/Controller"
    type:     annotation

AmPresenceBundle:
    resource: "@AmPresenceBundle/Controller"
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal